src/objects/Cart__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Carts</relationshipLabel>
        <relationshipName>Carts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Ordered</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TotalAmount__c</fullName>
        <label>Total Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Cart</label>
    <nameField>
        <label>Cart Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Carts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CartItem__c.object
<CustomObject>
    <fields>
        <fullName>Cart__c</fullName>
        <label>Cart</label>
        <referenceTo>Cart__c</referenceTo>
        <relationshipLabel>Cart Items</relationshipLabel>
        <relationshipName>Cart_Items</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Item__c</fullName>
        <label>Item</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>Cart Items</relationshipLabel>
        <relationshipName>Cart_Items1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total__c</fullName>
        <formula>Quantity__c *  Item__r.Price__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Cart Item</label>
    <nameField>
        <label>Cart Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cart Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Item__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>64</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CartController.cls
public with sharing class CartController {
	// return total amount of item in cart TODO: use return value
	@AuraEnabled
	public static Decimal addItemToCart(Id accountId, Id itemId) {
		List<Cart__c> carts = [SELECT Id FROM Cart__c WHERE Account__c = :accountId AND Status__c != 'Ordered' LIMIT 1];
		Cart__c cart;

		if (carts.isEmpty()) {
			cart = new Cart__c(Account__c = accountId, Status__c = 'New');
			insert cart;
		} else {
			cart = carts[0];
		}

		Id cartId = cart.Id;

		List<CartItem__c> existingItems =
			[SELECT Id, Quantity__c FROM CartItem__c WHERE Cart__c=:cart.Id AND Item__c = :itemId LIMIT 1];
		CartItem__c item;

		if (existingItems.isEmpty()) {
			item = new CartItem__c(Cart__c = cartId, Item__c = itemId, Quantity__c = 1);
			insert item;
		} else {
			item = existingItems[0];
			item.Quantity__c += 1;
			update item;
		}

		return item.Quantity__c;
	}

	@AuraEnabled
	public static List<CartItem__c> getCartItems(Id accountId) {
		List<Cart__c> carts = [SELECT Id FROM Cart__c WHERE Account__c = :accountId AND Status__c != 'Ordered' LIMIT 1];

		if (carts.isEmpty()) {
			return new List<CartItem__c>();
		}

		return [
			SELECT Id, Item__r.Name__c, Quantity__c, Total__c, Cart__r.TotalAmount__c
				FROM CartItem__c
				WHERE Cart__c = :carts[0].Id
		];
	}

}