src/objects/Item__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>254</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Family__c</fullName>
        <label>Family</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>For Education</fullName>
                </value>
                <value>
                    <fullName>For Gaming</fullName>
                </value>
                <value>
                    <fullName>For Graphics</fullName>
                </value>
                <value>
                    <fullName>For Programming</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Image__c</fullName>
        <description>link to image</description>
        <label>Image</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>64</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Phone</fullName>
                    <default>true</default>
                    <label>Phone</label>
                </value>
                <value>
                    <fullName>Laptop</fullName>
                </value>
                <value>
                    <fullName>Tablet</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ItemController.cls
public with sharing class ItemController {
	@AuraEnabled(cacheable = true)
	public static List<Item__c> getItemsBySearch(String searchKey,
												 List<String> familyFilters,
												 List<String> typeFilters) {
		String search = '%' + searchKey + '%';

		// if some filter is null or empty, we will ignore it
		// just by placing %%, what means always TRUE (every word contains '' lol)
		String ignoreFamily;
		String ignoreType;

		if (familyFilters == null || familyFilters.isEmpty()) {
			ignoreFamily = '%%';
		}

		if (typeFilters == null || typeFilters.isEmpty()) {
			ignoreType = '%%';
		}

		List<Item__c> results = [
			SELECT ID, Name__c, Description__c, Type__c, Family__c, Price__c, Image__c
			FROM Item__c
				WHERE (Name__c LIKE :search OR Description__c LIKE :search)
				AND ( Family__c IN :familyFilters OR Family__c LIKE :ignoreFamily)
				AND ( Type__c IN :typeFilters OR Type__c LIKE :ignoreType)
				LIMIT 50
		];

		return results;
	}


	@AuraEnabled(cacheable = true)
	public static Map<String, List<String>> getPicklistValues() {
		Map<String, List<String>> picklists = new Map<String, List<String>>();

		Schema.DescribeFieldResult familyField = Item__c.Family__c.getDescribe();
		List<Schema.PicklistEntry> familyEntries = familyField.getPicklistValues();
		List<String> familyValues = new List<String>();
		for (Schema.PicklistEntry entry : familyEntries) {
			familyValues.add(entry.getValue());
		}
		picklists.put('Family', familyValues);

		Schema.DescribeFieldResult typeField = Item__c.Type__c.getDescribe();
		List<Schema.PicklistEntry> typeEntries = typeField.getPicklistValues();
		List<String> typeValues = new List<String>();
		for (Schema.PicklistEntry entry : typeEntries) {
			typeValues.add(entry.getValue());
		}
		picklists.put('Type', typeValues);

		return picklists;
	}

	@AuraEnabled
	public static void createItem(String name,
								  String description,
								  Decimal price,
								  String type,
								  String family,
								  String image) {
		try {
			Item__c newItem = new Item__c(
					Name = name,
					Name__c = name,
					Description__c = description,
					Price__c = price,
					Type__c = type,
					Family__c = family,
					Image__c = image
			);
			insert newItem;
		} catch (Exception e) {
			throw new AuraHandledException('Failed to insert item: ' + e.getMessage());
		}
	}


	@AuraEnabled(cacheable = true)
	public static List<String> getTypeOptions() {
		return getPicklistValues().get('Type');
	}

	@AuraEnabled(cacheable = true)
	public static List<String> getFamilyOptions() {
		return getPicklistValues().get('Family');
	}

}