src/objects/Item__c.object
<CustomObject>
    <fields>
        <fullName>Family__c</fullName>
        <label>Family</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>For Education</fullName>
                </value>
                <value>
                    <fullName>For Gaming</fullName>
                </value>
                <value>
                    <fullName>For Graphics</fullName>
                </value>
                <value>
                    <fullName>For Programming</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Phone</fullName>
                    <default>true</default>
                    <label>Phone</label>
                </value>
                <value>
                    <fullName>Laptop</fullName>
                </value>
                <value>
                    <fullName>Tablet</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FilterService.cls
public class FilterService {
	@AuraEnabled(cacheable = true)
	public static List<String> getFamilyOptions() {
		return getPicklistValues(Item__c.Family__c);
	}

	@AuraEnabled(cacheable = true)
	public static List<String> getTypeOptions() {
		return getPicklistValues(Item__c.Type__c);
	}

	private static List<String> getPicklistValues(SObjectField field) {
		DescribeFieldResult objField = field.getDescribe();
		List<PicklistEntry> entries = objField.getPicklistValues(); // all picklist fields

		List<String> values = new List<String>();

		for (PicklistEntry entry : entries) {
			values.add(entry.getValue());
		}

		return values;
	}
}